Cmake maloc
Electrostatics/FETK pull request #4
Opened 2021-03-19 19:08 UTC by nsoblath

Basic Maloc build works and has been integrated into the top-level FETK build

2021-03-19 19:09 UTC, nsoblath commented
Closes #2

2021-03-25 16:19 UTC, intendo requested changes
@nsoblath I had no idea about the "Review Process" would not send you my comments until I submitted change requests.

2021-03-25 18:58 UTC, nsoblath commented on maloc/src/config/maloccf.h.in
> +#cmakedefine ACCEPT_USES_UINT 1
I can certainly take the values out.  However, I may be missing something, but I don't see where in the documentation says that there shouldn't be values after the cmakedefine variables.  The page for the `configure_file` command says:

> Furthermore, input lines of the form
>   
> `#cmakedefine VAR ...`
>
> will be replaced with either
>   
> `#define VAR ...`
>
> or
>   
> /* #undef VAR */
> depending on whether VAR is set in CMake to any value not considered a false constant by the if() command. The "..." 
> content on the line after the variable name, if any, is processed as above. Input file lines of the form #cmakedefine01 VAR will be replaced with either #define VAR 1 or #define VAR 0 similarly.

It seems like the discussion of the "'...' content" is referring to values after the variable definition.

2021-03-25 21:34 UTC, intendo commented on maloc/src/config/maloccf.h.in
> +#cmakedefine ACCEPT_USES_UINT 1
@nsoblath ,
I think you should look at [CMakeChecks.basic-checks.cmake](https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/build-system/cmake/CMakeChecks.basic-checks.cmake) as an example on how to update `maloc/src/CMakeLists.txt`. 

Most of the `...` results can be defined by checking for values in `maloc/src/config/maloccf.h.in`. Adding the following to the `maloc/src/CMakeLists.txt` before the `configure_file` should fill in the correct `#define` value for `HAVE_ARPA_INET_H` in `maloc/src/config/maloccf.h.in` line 71 and put the correct result in the target `maloccf.h` file:
```
check_include_file(arpa/inet.h HAVE_ARPA_INET_H)
```
Likewise, for type sizes like line 68 in `maloc/src/config/maloccf.h.in`, you can add the following before the `configure_file` in `maloc/src/CMakeLists.txt`:
```
include(CheckTypeSize)
check_type_size("unsigned long" ACCEPT_USES_ULONG)
```

2021-04-02 21:19 UTC, intendo commented on maloc/src/config/maloccf.h.in
> +#cmakedefine ACCEPT_USES_UINT 1
@nsoblath we still need to get rid of all the `1`s in the #cmakedefine directives.

2021-04-02 21:20 UTC, intendo requested changes
@nsoblath we still need to get rid of all the 1s in the #cmakedefine directives.

2021-04-03 00:08 UTC, nsoblath commented
@intendo I believe all of the requested changes and other things we've talked about have been addressed.  Please take a look and let me know.

2021-04-03 00:13 UTC, intendo approved these changes

2021-04-03 00:18 UTC, merged